[versions]
agp = "8.8.2"
dokka = "2.0.0"
kotlin = "2.1.10"

[libraries]
# implementation
core-ktx = "androidx.core:core-ktx:1.15.0"
kotlin-bom = "org.jetbrains.kotlin:kotlin-bom:2.1.10"
appcompat = "androidx.appcompat:appcompat:1.7.0"
material = "com.google.android.material:material:1.12.0"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"

# implementation-plugins
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.10"

# test-implementation
junit = "junit:junit:4.13.2"

#android-test-implementation
androidx-test-ext-junit = "androidx.test.ext:junit:1.2.1"
espresso-core = "androidx.test.espresso:espresso-core:3.6.1"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
